name: shang_shop_vender_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  mqtt_client: ^10.3.0
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.8
  equatable: ^2.0.5
  pull_to_refresh_flutter3: ^2.0.2


  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.2

  # Networking
  pretty_dio_logger: ^1.3.1
  logger: ^2.3.0
  dio: ^5.5.0+1
  retrofit: ^4.1.0

  # Json Serialization
  json_annotation: ^4.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.1
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
